### ISSUE TITLE
HTML in Readme seems to have some trouble in package detail view

### ISSUE THREAD

**Issue by michael-spengler** [nestdotland/nest.land#268] opened 2020-09-13 00:06 UTC
Compare: https://github.com/drashland/dmm
With: https://nest.land/package/dmm

at the top - see:

![Screen Shot 2020-09-13 at 2 05 43 AM](https://user-images.githubusercontent.com/43786652/93007155-bb3c1380-f565-11ea-8333-52206ce28558.png)

**Comment by t8** [comment] 2020-09-13 04:10
Duplicate of #227. This is something we're looking to find a solution for. Right now, the only fix would be to change the source of the image tag from `logo.png` to `https://github.com/drashland/dmm/raw/master/logo.png`

**Closed by t8** 2020-09-13 04:10 UTC
